id: P008048
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC34
  title: གུང་རུ་རྒྱལ་མཚན་བཟང་པོའི་སྟོང་ཐུན་དང་རྣམ་ཐར།
  author: ''
  volumes:
    748dca2a865e4affb27ad3059ca177ad:
      image_group_id: I2PD18911
      title: ''
      volume_number: 1
      total_pages: 200
ebook_metadata:
  title: གུང་རུ་རྒྱལ་མཚན་བཟང་པོའི་སྟོང་ཐུན་དང་རྣམ་ཐར།
  author: ''
  sku: P008048
  cover: cover.jpg
  layers:
  - pagination
